In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,4,9,16,25,36])

In [4]:
c = a * b 
print(c)

[  1   8  27  64 125 216]


In [5]:
#给定值生成ndarray
#ndarray是Numpy的核心对象，numpy.array()函数是它最简单的构造方式
a = np.array([1,2,3,4,5,6])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
#np.empty()用随机值构造数组,速度最快
a1 = np.empty(3)
print(a1)

#构建2*3举证
a2 = np.empty((2,3))
print(a2)

[  2.68156159e+154   2.68156159e+154   9.88131292e-324]
[[  4.94065646e-324   9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323   2.96439388e-323]]


In [10]:
#np.eye() 构造只有对角线元素卫1的矩阵
a3 = np.eye(5,5)
print(a3)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [12]:
#构造全为0的数组
a4 = np.zeros(4)
print(a4)
#构造全为1的数组
a5 = np.ones(4)
print(a5)

[ 0.  0.  0.  0.]
[ 1.  1.  1.  1.]


In [15]:
#随机生成一个2*5的二维数组
a6 = np.random.rand(2,5)
print(a6)

[[ 0.18538484  0.31006249  0.689224    0.5839446   0.96381664]
 [ 0.13613226  0.84306532  0.65147104  0.21962733  0.48223917]]


In [17]:
#下三角单位举证
a7 = np.tri(3)
print(a7)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 1.  1.  1.]]


In [19]:
# arange() linspace() logspance() 等函数可以在给定的取值范围内用步长，比值等规则构造出数组序列

#在1-20之间生成7个元素
b1 = np.linspace(1, 20, num=7)
print(b1)

[  1.           4.16666667   7.33333333  10.5         13.66666667
  16.83333333  20.        ]


In [21]:
#在1-20之间每7个值生成一个元素
b2 = np.arange(1, 20, step = 7)
print(b2)

[ 1  8 15]


In [22]:
#在10^1-10^20之间取7哥指数值
b3 = np.logspace(1, 20, num=7, base=10)
print(b3)

[  1.00000000e+01   1.46779927e+04   2.15443469e+07   3.16227766e+10
   4.64158883e+13   6.81292069e+16   1.00000000e+20]


In [23]:
#随机采样
#随机生成一个2*5de 二维数组
b4 = np.random.rand(2,5)
print(b4)

[[ 0.82126758  0.99261292  0.10744498  0.40613316  0.46492734]
 [ 0.44390338  0.01356532  0.42768395  0.04004796  0.35706173]]


In [25]:
#按均值1，标准差0.5的正太分布生成5个随机数
b5 = np.random.normal(1, 0.5, size = 5)
print(b5)

[ 1.22573965  0.04515477  1.37480834  0.70694157  1.92741216]


In [27]:
#切片操作
#切片的基本语法是一个i:j:k的索引器
x= np.array([0,1,2,3,4,5,6,7,8,9])
print(x)
print(x[2:7:2]) #从索引为2开始，每两步读取一个，到7未知

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [31]:
# i,j,k取值允许为负值，含义是从倒数索引
print(x[-7:-1:])
print(x[-7:-1])
print(x[7:1:-2])

[3 4 5 6 7 8]
[3 4 5 6 7 8]
[7 5 3]


In [32]:
#迭代一维数组，可以直接迭代ndarray已访问所有元素
for i in x:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,

In [35]:
#对于多维数组可以使用ndenumerate()函数迭代的同事获取元素下标
x = np.array([[1,2,],[5,6,],[9,10,]])
print(x)
for index, value in np.ndenumerate(x):
    print(index, ":", value)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
(0, 0) : 1
(0, 1) : 2
(1, 0) : 5
(1, 1) : 6
(2, 0) : 9
(2, 1) : 10


In [36]:
#唯一列表
a = np.array([1,2,6,4,2,3,2])
b = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print(b)
#第一个返结果： 数组
#第二个结果：  数组中每个元素在原始数组中的索引
#第三个结果：  原数组中每个元素在结果数组中的索引
#第四个结果    结果数组中每个元素在原始数组数组中的计数


(array([1, 2, 3, 4, 6]), array([0, 1, 5, 3, 2]), array([0, 1, 4, 3, 1, 2, 1]), array([1, 3, 1, 1, 1]))
